apiVersion: v1
kind: ConfigMap

metadata:
  name: next-config
  namespace: dev
  annotations:
    argocd.argoproj.io/sync-wave: "-2"

data:
  NEXTAUTH_URL: "next.rullabcd.my.id"
  NODE_ENV: "production"
