apiVersion: v1
kind: Secret

metadata:
  name: next-secrets
  namespace: dev
  annotations:
    argocd.argoproj.io/sync-wave: "0"

type: Opaque
stringData:
  DATABASE_URL: "mysql://rullabcd:rullabcd@database-1.cxsciarp4wxb.us-east-1.rds.amazonaws.com:3306/demo"
